import {
  Home, Users, Church, Shield, HandHelping,
  Layers, Calendar, Megaphone, DollarSign,
  FileText, User, Settings, LogOut, Key,
  Heart, Info, Image, Youtube, CalendarDays,
  ClipboardList,
} from "lucide-react";

const adminRoles = ["admin", "superadmin"];
const allRoles = ["admin", "superadmin", "ump", "upa", "uph", "saf", "ucp", "diaconia", "conselho", "ministerio", "ebd", "member"];
const staffRoles = ["admin", "superadmin", "ump", "upa", "uph", "saf", "ucp", "diaconia", "conselho", "ministerio", "ebd"];

export const menuItems = [
  {
    title: "MENU",
    items: [
      {
        icon: Home,
        label: "Início",
        href: "/member",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: Info,
        label: "Saiba Mais",
        href: "/about",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: CalendarDays,
        label: "Agenda Semanal",
        href: "/agenda",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Users,
        label: "Membros",
        href: "/list/members",
        visible: adminRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: Church,
        label: "Sociedades Internas",
        href: "/list/internalsociety",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Shield,
        label: "Conselho",
        href: "/list/council",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: HandHelping,
        label: "Diaconia",
        href: "/list/diaconate",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Layers,
        label: "Ministérios",
        href: "/list/ministry",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Calendar,
        label: "Eventos da Igreja",
        href: "/list/events",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Calendar,
        label: "Eventos",
        href: "/list/events",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        icon: ClipboardList,
        label: "Presença",
        href: "/list/attendance",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        icon: Megaphone,
        label: "Anúncios",
        href: "/list/notice",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: Youtube,
        label: "Sermões",
        href: "/sermons",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Image,
        label: "Galeria",
        href: "/gallery",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Heart,
        label: "Dízimos e Ofertas",
        href: "/tithes",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: DollarSign,
        label: "Financeiro",
        href: "/list/finance",
        visible: adminRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: FileText,
        label: "Documentos",
        href: "/list/documents",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: Key,
        label: "Credenciais",
        href: "/admin/credenciais",
        visible: adminRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: DollarSign,
        label: "Financeiro",
        href: "/list/finance",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
    ],
  },
  {
    title: "OTHER",
    items: [
      {
        icon: User,
        label: "Perfil",
        href: "/profile",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: Settings,
        label: "Configurações",
        href: "/settings",
        visible: adminRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: LogOut,
        label: "Logout",
        href: "/logout",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
    ],
  },
];