import {
  Home, Users, Church, Shield, HandHelping,
  Layers, Calendar, Megaphone, DollarSign,
  FileText, User, Settings, LogOut, Key,
  Heart, Info, Image, Youtube, CalendarDays,
  ClipboardList, CalendarRange, MessageSquare,
  Camera, BarChart2, Package, CheckSquare, CalendarCheck,
  Inbox, Cross, BookOpen, BookMarked, Activity,
} from "lucide-react";

const pastorRoles = ["pastor", "superadmin"];
const adminRoles = ["admin", "superadmin", "pastor"];
const allRoles = ["admin", "superadmin", "pastor", "ump", "upa", "uph", "saf", "ucp", "diaconia", "conselho", "ministerio", "ebd", "superintendente", "member"];
const staffRoles = ["admin", "superadmin", "pastor", "ump", "upa", "uph", "saf", "ucp", "diaconia", "conselho", "ministerio", "ebd", "superintendente"];
// Papéis de grupo sem admin (o admin já tem o item "Membros" próprio no contexto de sociedade)
const groupStaffRoles = ["ump", "upa", "uph", "saf", "ucp", "diaconia", "conselho", "ministerio", "ebd", "superintendente"];

export const menuItems = [
  {
    title: "MENU",
    items: [
      {
        // Exclusivos da guia do Pastor — só aparecem dentro de /pastor.
        icon: Cross,
        label: "Painel do Pastor",
        href: "/pastor",
        group: "Pastor",
        visible: pastorRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
        showOnlyInPastor: true,
      },
      {
        icon: BookOpen,
        label: "Diário",
        href: "/pastor/diario",
        group: "Pastor",
        visible: pastorRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
        showOnlyInPastor: true,
      },
      {
        icon: BookMarked,
        label: "Meus Sermões",
        href: "/pastor/sermoes",
        group: "Pastor",
        beta: true,
        visible: pastorRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
        showOnlyInPastor: true,
      },
      {
        icon: Home,
        label: "Início",
        href: "/member",
        group: "Principal",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: CalendarRange,
        label: "Calendário Geral",
        href: "/calendario-geral",
        group: "Principal",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: CalendarDays,
        label: "Agenda Semanal",
        href: "/agenda",
        group: "Principal",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Info,
        label: "Saiba Mais",
        href: "/about",
        group: "Principal",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Users,
        label: "Membros",
        href: "/list/members",
        group: "Principal",
        visible: adminRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: Activity,
        label: "Acessos",
        href: "/admin/acessos",
        group: "Principal",
        beta: true,
        visible: ["admin", "superadmin"],
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Inbox,
        label: "Visitantes",
        href: "/list/visitantes",
        group: "Principal",
        visible: adminRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        // Versão para o contexto de sociedade/grupo — resolve para /<role>/membros
        icon: Users,
        label: "Membros",
        href: "/list/members",
        group: "Principal",
        visible: groupStaffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        // Lista de visitantes do grupo — resolve para /<role>/visitantes
        icon: Inbox,
        label: "Visitantes",
        href: "/visitantes",
        group: "Principal",
        visible: groupStaffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },

      {
        icon: Church,
        label: "Sociedades Internas",
        href: "/list/internalsociety",
        group: "Grupos",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Shield,
        label: "Conselho",
        href: "/conselho",
        group: "Grupos",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: HandHelping,
        label: "Diaconia",
        href: "/diaconia",
        group: "Grupos",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Layers,
        label: "Ministérios",
        href: "/ministerio",
        group: "Grupos",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },

      {
        icon: Calendar,
        label: "Eventos da Igreja",
        href: "/list/events",
        group: "Comunicação",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Calendar,
        label: "Eventos",
        href: "/list/events",
        group: "Comunicação",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        icon: Megaphone,
        label: "Anúncios",
        href: "/list/announcements",
        group: "Comunicação",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: MessageSquare,
        label: "Mensagens",
        href: "/list/broadcasts",
        group: "Comunicação",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        icon: Youtube,
        label: "Sermões",
        href: "/sermons",
        group: "Comunicação",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Image,
        label: "Galeria",
        href: "/gallery",
        group: "Comunicação",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: Camera,
        label: "Galeria",
        href: "/galeria",
        group: "Comunicação",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },

      {
        icon: ClipboardList,
        label: "Presença",
        href: "/list/attendance",
        group: "Gestão",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        icon: Heart,
        label: "Dízimos e Ofertas",
        href: "/tithes",
        group: "Gestão",
        visible: allRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: DollarSign,
        label: "Financeiro",
        href: "/list/finance",
        group: "Gestão",
        visible: adminRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },
      {
        icon: DollarSign,
        label: "Financeiro",
        href: "/list/finance",
        group: "Gestão",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        icon: FileText,
        label: "Documentos",
        href: "/list/documents",
        group: "Gestão",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: BarChart2,
        label: "Relatórios",
        href: "/relatorios",
        group: "Gestão",
        visible: staffRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
      },
      {
        icon: Key,
        label: "Credenciais",
        href: "/admin/credenciais",
        group: "Gestão",
        visible: adminRoles,
        hiddenForSociedades: true,
        showOnlyForSociedades: false,
      },

      {
        // Exclusivos da Diaconia — só aparecem navegando dentro de /diaconia.
        // `visible` filtra pelo papel do usuário; `onlyForRoleContext` filtra
        // pelo grupo que está aberto (sem ele, um admin veria estes itens
        // também dentro de UMP, SAF, etc.).
        icon: Package,
        label: "Inventário",
        href: "/diaconia/inventario",
        group: "Diaconia",
        visible: ["diaconia", "admin", "superadmin"],
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
        onlyForRoleContext: ["diaconia"],
      },
      {
        icon: CheckSquare,
        label: "Tarefas",
        href: "/diaconia/tarefas",
        group: "Diaconia",
        visible: ["diaconia", "admin", "superadmin"],
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
        onlyForRoleContext: ["diaconia"],
      },
      {
        icon: CalendarCheck,
        label: "Escala",
        href: "/diaconia/escala",
        group: "Diaconia",
        visible: ["diaconia", "admin", "superadmin"],
        hiddenForSociedades: false,
        showOnlyForSociedades: true,
        onlyForRoleContext: ["diaconia"],
      },
    ],
  },
  {
    title: "OTHER",
    items: [
      {
        icon: User,
        label: "Perfil",
        href: "/profile",
        group: "Conta",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: Settings,
        label: "Configurações",
        href: "/settings",
        group: "Conta",
        visible: adminRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
      {
        icon: LogOut,
        label: "Logout",
        href: "/logout",
        group: "Conta",
        visible: allRoles,
        hiddenForSociedades: false,
        showOnlyForSociedades: false,
      },
    ],
  },
];
